app:
    info:
        name: "Spring cloud client application2"
        description: "Test spring cloud client application2"
    color:
        name: "GREEN2"
        proto:
            name: "PROTO_GREEN2"
    car:
        model: "VW2"
#    connection:
#        service:
#            simple:
#                color: false
#                car: true