app:
    info:
        name: "Spring cloud client application"
        description: "Test spring cloud client application"
    color:
        name: "RED"
        proto:
            name: "PROTO_RED"
    car:
        model: "BMW"