app:
    info:
        name: "Spring cloud client application5"
        description: "Test spring cloud client application5"
    color:
        name: "GREEN5"
        proto:
            name: "PROTO_GREEN5"
    car:
        model: "VW5"
    connection:
        service:
            simple:
                color: false
                car: true
    ui:
        featureToggles:
            test1: true
            test2: true
            test3: false
    